---
deployment:
  tasks:
    # cPanel runs these when it deploys the repo.
    - export DEPLOYPATH=/home/singledads/public_html/test/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
